# This file adheres to the tset C++ developer workflow.
# See the documentation in the Makefile for more information.
# Do not edit this file.

from conans import ConanFile, CMake
import glob
import os


class CppDevContainerTestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def __init__(self, *args, **kwargs):
        config = dict(load_config_file(os.path.join('out', '.env')))

        def convert_to_conan_recipe(requirements):
            if requirements is None or len(requirements) == 0:
                return requirements
            user = config.get('CONAN_USER', '')
            channel = config.get('CONAN_CHANNEL', '')
            latest = config.get('CONAN_LATEST', 'latest')
            return requirements.replace('{latest}', latest).replace('{user}', user).replace('{channel}', channel).split(',')

        CppDevContainerTestConan.requires = convert_to_conan_recipe(config.get('CONAN_REQUIRE', None))

        super().__init__(*args, **kwargs)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        for test_file in glob.glob(os.path.join("bin", "test*")):
            self.run(f"LD_LIBRARY_PATH={os.path.abspath('bin')} {test_file}")


def load_config_file(filename): 
    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue

            k, v = line.split('=', 1)
            k, v = k.strip(), v.strip()

            if len(v) > 0:
                quoted = v[0] == v[len(v) - 1] in ['"', "'"]
                if quoted:
                    v = v[1:-1]

            yield k, v
